/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
/**
 *
 * @author brener
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form Main_Screen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundImage1 = new gui.BackgroundImage();
        btnRent = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xtra-vision Software");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 680));

        backgroundImage1.setBorder(null);
        backgroundImage1.setFont(new java.awt.Font("Bitstream Charter", 1, 48)); // NOI18N
        backgroundImage1.setImg(new ImageIcon("src/images/background.jpeg"));
        backgroundImage1.setPreferredSize(new java.awt.Dimension(1280, 680));

        btnRent.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnRent.setText("Rent a movie");
        btnRent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRent.setFocusable(false);
        btnRent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnReturn.setText("Return a movie");
        btnReturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReturn.setFocusable(false);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReturn.setMaximumSize(new java.awt.Dimension(159, 35));
        btnReturn.setMinimumSize(new java.awt.Dimension(159, 35));
        btnReturn.setPreferredSize(new java.awt.Dimension(159, 35));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lblTitle.setForeground(java.awt.Color.white);
        lblTitle.setText("Xtra-vision");

        javax.swing.GroupLayout backgroundImage1Layout = new javax.swing.GroupLayout(backgroundImage1);
        backgroundImage1.setLayout(backgroundImage1Layout);
        backgroundImage1Layout.setHorizontalGroup(
            backgroundImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundImage1Layout.createSequentialGroup()
                        .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundImage1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 621, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundImage1Layout.setVerticalGroup(
            backgroundImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundImage1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addGroup(backgroundImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
        RentMovie RentMovie = new RentMovie();
        RentMovie.setVisible(true);
                
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        ReturnMovie ReturnMovie = new ReturnMovie();
        ReturnMovie.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //Create and display the screen
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.BackgroundImage backgroundImage1;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
